import { StyleSheet } from "react-native";
import { colors } from "./colors.js";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: { flexGrow: 1, paddingBottom: 30 },
  heroSection: { paddingTop: 40, paddingBottom: 30, paddingHorizontal: 24, alignItems: "center" },
  illustrationWrapper: { marginBottom: 24 },
  illustrationBg: {
    position: "relative",
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "#FFF5F3",
    justifyContent: "center",
    alignItems: "center",
  },
  mainIconCircle: { width: 110, height: 110, borderRadius: 55, backgroundColor: "#FFE8E8", justifyContent: "center", alignItems: "center" },
  dollarBadge: { position: "absolute", bottom: 8, right: 8, width: 50, height: 50, borderRadius: 25, justifyContent: "center", alignItems: "center" },
  dollarSymbol: { fontSize: 24, fontWeight: "bold", color: colors.background },
  trendingBadge: { position: "absolute", top: 15, left: 12, width: 32, height: 32, borderRadius: 16, backgroundColor: colors.background, justifyContent: "center", alignItems: "center" },
  titleContainer: { marginBottom: 10 },
  title: { fontSize: 28, fontWeight: "700", textAlign: "center", lineHeight: 36 },
  subtitle: { fontSize: 13, color: colors.gray, textAlign: "center", lineHeight: 18 },
  formCard: { marginHorizontal: 20, marginTop: 20, backgroundColor: colors.background, borderRadius: 24, padding: 20, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 4 },
  tabContainer: { flexDirection: "row", backgroundColor: colors.lightGray, borderRadius: 12, padding: 4, marginBottom: 20 },
  tab: { flex: 1 },
  tabInactive: { justifyContent: "center", alignItems: "center" },
  tabGradient: { paddingVertical: 10, borderRadius: 10, alignItems: "center" },
  tabTextActive: { color: colors.background, fontSize: 14, fontWeight: "600" },
  tabTextInactive: { color: colors.gray, fontSize: 14, fontWeight: "600", paddingVertical: 10, textAlign: "center" },
  formHeader: { marginBottom: 20 },
  formTitle: { fontSize: 22, fontWeight: "700", color: colors.text, marginBottom: 4 },
  formSubtitle: { fontSize: 13, color: colors.gray },
  inputWrapper: { marginBottom: 12 },
  inputContainer: { flexDirection: "row", alignItems: "center", backgroundColor: colors.lightGray, borderRadius: 12, paddingHorizontal: 14, borderWidth: 1.5, borderColor: "transparent" },
  inputContainerFocused: { backgroundColor: colors.background, borderColor: colors.primary },
  inputIcon: { marginRight: 10 },
  input: { flex: 1, paddingVertical: 14, fontSize: 14, color: colors.text },
  errorContainer: { flexDirection: "row", alignItems: "center", backgroundColor: "#FEE2E2", paddingHorizontal: 12, paddingVertical: 10, borderRadius: 8, marginBottom: 12, gap: 8 },
  errorText: { flex: 1, fontSize: 12, color: "#DC2626" },
  forgotPassword: { alignSelf: "flex-end", marginBottom: 20 },
  forgotPasswordText: { fontSize: 12, color: colors.primary, fontWeight: "600" },
  submitButtonWrapper: { marginBottom: 12 },
  submitButton: { paddingVertical: 14, borderRadius: 12, alignItems: "center", shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 6 },
  submitButtonText: { color: colors.background, fontSize: 15, fontWeight: "600" },
  createAccountLink: { alignItems: "center", marginBottom: 20 },
  createAccountText: { fontSize: 13, color: colors.gray },
  createAccountTextBold: { color: colors.primary, fontWeight: "600" },
  dividerContainer: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  dividerLine: { flex: 1, height: 1, backgroundColor: colors.border },
  dividerText: { fontSize: 12, color: colors.gray, paddingHorizontal: 14 },
  googleButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 12, borderRadius: 12, borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.background, gap: 10 },
  googleButtonText: { fontSize: 14, fontWeight: "600", color: colors.text },
  termsText: { fontSize: 11, color: colors.gray, textAlign: "center", marginTop: 16, lineHeight: 16 },
  termsLink: { color: colors.primary, fontWeight: "600" },
});
